import sys
sys.path.insert(0, '.')

from database import SessionLocal, engine, Base
from models import User, Campaign, SalesPitch, LeadScore, MarketAnalysis, BusinessInsight
from passlib.context import CryptContext
from datetime import datetime, timedelta
import random

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

Base.metadata.create_all(bind=engine)

db = SessionLocal()

try:
    existing = db.query(User).first()
    if existing:
        print("Database already seeded. Skipping...")
        db.close()
        exit(0)

    users = []
    hashed_password = pwd_context.hash("password123")

    admin = User(
        email="admin@marketmind.com",
        hashed_password=hashed_password,
        full_name="Admin User",
        role="admin"
    )
    db.add(admin)
    users.append(admin)

    demo = User(
        email="demo@marketmind.com",
        hashed_password=hashed_password,
        full_name="Demo User",
        role="user"
    )
    db.add(demo)
    users.append(demo)

    db.commit()
    print("Created users: admin@marketmind.com, demo@marketmind.com (password: password123)")

    industries = ["Technology", "Finance", "Healthcare", "E-commerce", "SaaS"]
    products = ["CRM Platform", "Analytics Dashboard", "AI Assistant", "Marketing Suite", "Sales Tool"]
    campaign_goals = ["Brand Awareness", "Lead Generation", "Sales Conversion", "Product Launch"]
    customer_types = ["Enterprise", "SMB", "Startup", "B2B", "B2C"]

    for user in users:
        for i in range(random.randint(2, 5)):
            campaign = Campaign(
                user_id=user.id,
                product_name=random.choice(products),
                industry=random.choice(industries),
                target_audience="Business decision makers",
                campaign_goal=random.choice(campaign_goals),
                generated_content="Sample campaign content generated by AI for demonstration purposes.",
                created_at=datetime.utcnow() - timedelta(days=random.randint(1, 30))
            )
            db.add(campaign)

        for i in range(random.randint(2, 4)):
            pitch = SalesPitch(
                user_id=user.id,
                product=random.choice(products),
                customer_type=random.choice(customer_types),
                generated_content="Sample sales pitch content for product demonstration.",
                created_at=datetime.utcnow() - timedelta(days=random.randint(1, 30))
            )
            db.add(pitch)

        for i in range(random.randint(3, 6)):
            lead = LeadScore(
                user_id=user.id,
                company_size=random.choice(["11-50", "51-200", "201-500", "1000+"]),
                industry=random.choice(industries),
                budget=random.choice(["Low", "Medium", "High", "Enterprise"]),
                engagement_level=random.choice(["Low", "Medium", "High"]),
                score=random.uniform(20, 95),
                priority=random.choice(["High", "Medium", "Low"]),
                generated_content="Sample lead analysis content for demonstration.",
                created_at=datetime.utcnow() - timedelta(days=random.randint(1, 30))
            )
            db.add(lead)

        for i in range(random.randint(1, 3)):
            analysis = MarketAnalysis(
                user_id=user.id,
                industry=random.choice(industries),
                generated_content="Sample market analysis content generated by AI.",
                created_at=datetime.utcnow() - timedelta(days=random.randint(1, 30))
            )
            db.add(analysis)

        for i in range(random.randint(1, 2)):
            insight = BusinessInsight(
                user_id=user.id,
                business_description="B2B SaaS company providing productivity tools for enterprises",
                generated_content="Sample business insight content for strategic planning.",
                created_at=datetime.utcnow() - timedelta(days=random.randint(1, 30))
            )
            db.add(insight)

    db.commit()
    print("Seed data created successfully!")

except Exception as e:
    print(f"Error seeding database: {e}")
    db.rollback()
finally:
    db.close()
